from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

import datetime


T = TypeVar("T", bound="PostPaths")


@_attrs_define
class PostPaths:
    """
    Attributes:
        autogenerated (bool):
        footprint (str): Max length: 255
        goal_pos_id (str):
        last_used (datetime.datetime):
        length (float):
        map_crc (str): Min length: 32, Max length: 32
        path (str):
        start_pos_id (str):
        time (float):
        valid (bool):
        guid (str | Unset):
    """

    autogenerated: bool
    footprint: str
    goal_pos_id: str
    last_used: datetime.datetime
    length: float
    map_crc: str
    path: str
    start_pos_id: str
    time: float
    valid: bool
    guid: str | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        autogenerated = self.autogenerated

        footprint = self.footprint

        goal_pos_id = self.goal_pos_id

        last_used = self.last_used.isoformat()

        length = self.length

        map_crc = self.map_crc

        path = self.path

        start_pos_id = self.start_pos_id

        time = self.time

        valid = self.valid

        guid = self.guid

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "autogenerated": autogenerated,
                "footprint": footprint,
                "goal_pos_id": goal_pos_id,
                "last_used": last_used,
                "length": length,
                "map_crc": map_crc,
                "path": path,
                "start_pos_id": start_pos_id,
                "time": time,
                "valid": valid,
            }
        )
        if guid is not UNSET:
            field_dict["guid"] = guid

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        autogenerated = d.pop("autogenerated")

        footprint = d.pop("footprint")

        goal_pos_id = d.pop("goal_pos_id")

        last_used = datetime.datetime.fromisoformat(d.pop("last_used"))

        length = d.pop("length")

        map_crc = d.pop("map_crc")

        path = d.pop("path")

        start_pos_id = d.pop("start_pos_id")

        time = d.pop("time")

        valid = d.pop("valid")

        guid = d.pop("guid", UNSET)

        post_paths = cls(
            autogenerated=autogenerated,
            footprint=footprint,
            goal_pos_id=goal_pos_id,
            last_used=last_used,
            length=length,
            map_crc=map_crc,
            path=path,
            start_pos_id=start_pos_id,
            time=time,
            valid=valid,
            guid=guid,
        )

        post_paths.additional_properties = d
        return post_paths

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
