from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

import datetime


T = TypeVar("T", bound="PutPath")


@_attrs_define
class PutPath:
    """
    Attributes:
        autogenerated (bool | Unset):
        footprint (str | Unset): Max length: 255
        goal_pos_id (str | Unset):
        last_used (datetime.datetime | Unset):
        length (float | Unset):
        map_crc (str | Unset): Min length: 32, Max length: 32
        path (str | Unset):
        start_pos_id (str | Unset):
        time (float | Unset):
        valid (bool | Unset):
    """

    autogenerated: bool | Unset = UNSET
    footprint: str | Unset = UNSET
    goal_pos_id: str | Unset = UNSET
    last_used: datetime.datetime | Unset = UNSET
    length: float | Unset = UNSET
    map_crc: str | Unset = UNSET
    path: str | Unset = UNSET
    start_pos_id: str | Unset = UNSET
    time: float | Unset = UNSET
    valid: bool | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        autogenerated = self.autogenerated

        footprint = self.footprint

        goal_pos_id = self.goal_pos_id

        last_used: str | Unset = UNSET
        if not isinstance(self.last_used, Unset):
            last_used = self.last_used.isoformat()

        length = self.length

        map_crc = self.map_crc

        path = self.path

        start_pos_id = self.start_pos_id

        time = self.time

        valid = self.valid

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update({})
        if autogenerated is not UNSET:
            field_dict["autogenerated"] = autogenerated
        if footprint is not UNSET:
            field_dict["footprint"] = footprint
        if goal_pos_id is not UNSET:
            field_dict["goal_pos_id"] = goal_pos_id
        if last_used is not UNSET:
            field_dict["last_used"] = last_used
        if length is not UNSET:
            field_dict["length"] = length
        if map_crc is not UNSET:
            field_dict["map_crc"] = map_crc
        if path is not UNSET:
            field_dict["path"] = path
        if start_pos_id is not UNSET:
            field_dict["start_pos_id"] = start_pos_id
        if time is not UNSET:
            field_dict["time"] = time
        if valid is not UNSET:
            field_dict["valid"] = valid

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        autogenerated = d.pop("autogenerated", UNSET)

        footprint = d.pop("footprint", UNSET)

        goal_pos_id = d.pop("goal_pos_id", UNSET)

        _last_used = d.pop("last_used", UNSET)
        last_used: datetime.datetime | Unset
        if isinstance(_last_used, Unset):
            last_used = UNSET
        else:
            last_used = datetime.datetime.fromisoformat(_last_used)

        length = d.pop("length", UNSET)

        map_crc = d.pop("map_crc", UNSET)

        path = d.pop("path", UNSET)

        start_pos_id = d.pop("start_pos_id", UNSET)

        time = d.pop("time", UNSET)

        valid = d.pop("valid", UNSET)

        put_path = cls(
            autogenerated=autogenerated,
            footprint=footprint,
            goal_pos_id=goal_pos_id,
            last_used=last_used,
            length=length,
            map_crc=map_crc,
            path=path,
            start_pos_id=start_pos_id,
            time=time,
            valid=valid,
        )

        put_path.additional_properties = d
        return put_path

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
