"""Convert MiR's REST API PDFs into Swagger 2.0 documents.

The support portal only publishes the API definitions as PDFs (generated by
swagger2markup + Asciidoctor from MiR's internal swagger doc, so the layout is
machine-regular). This module reverses that rendering:

- Operation sections: a ``METHOD /path`` heading followed by ``Parameters``
  and ``Responses`` tables.
- A ``Definitions`` section: one heading per model followed by a
  ``Name/Description/Schema`` (or ``Name/Schema``) property table.
- Tables that continue across a page break repeat their header row; a table
  with no new heading before it belongs to the previous section.
- Cells wrap mid-identifier (``PostCart_calibratio\\nns``): identifiers are
  reconstructed by stripping all whitespace, after peeling off the
  ``required``/``optional`` flag lines.

Fidelity is validated against MiR's official 3.5.4 swagger.json (the one
non-PDF artifact we have) — see tests and mir_spec_scraper.validate.compare.
"""

from __future__ import annotations

import re
from typing import Any

METHODS = ("GET", "POST", "PUT", "DELETE", "PATCH")
_OP_RE = re.compile(r"^(GET|POST|PUT|DELETE|PATCH)\s+(/\S*)$")
_DEF_NAME_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
_BASIC_RE = re.compile(r"^(string|integer|number|boolean|object|file)(?:\(([^)]+)\))?$")
_ARRAY_RE = re.compile(r"^<(.+)>array$")
_MAP_RE = re.compile(r"^<string,(.+)>map$")
_ENUM_RE = re.compile(r"^enum\((.*)\)$")


def _cell_lines(cell: str | None) -> list[str]:
    return [line.strip() for line in (cell or "").splitlines() if line.strip()]


def parse_name_cell(cell: str | None) -> tuple[str, bool]:
    """('Authorizatio\\nn\\nrequired') -> ('Authorization', True)."""
    required = False
    kept = []
    for line in _cell_lines(cell):
        if line in ("required", "optional"):
            required = required or line == "required"
            continue
        kept.append(line)
    return "".join(kept), required


def parse_schema_token(cell: str | None) -> dict[str, Any] | None:
    """Map a Schema cell to a swagger schema fragment (None for 'No Content')."""
    token = "".join((cell or "").split())
    if not token or token in ("NoContent", "none"):
        return None
    enum = _ENUM_RE.match(token)
    if enum:
        values = [v for v in enum.group(1).split(",") if v]
        return {"type": "string", "enum": values}
    array = _ARRAY_RE.match(token)
    if array:
        # "< object > array" is ambiguous: the source swagger sometimes has
        # items {type: object} and sometimes no items at all; both render the
        # same. Emit the majority form — they validate identically for the
        # payloads MiR actually sends.
        items = parse_schema_token(array.group(1))
        return {"type": "array", "items": items or {"type": "object"}}
    mapping = _MAP_RE.match(token)
    if mapping:
        values = parse_schema_token(mapping.group(1))
        return {"type": "object", "additionalProperties": values or {"type": "object"}}
    basic = _BASIC_RE.match(token)
    if basic:
        schema: dict[str, Any] = {"type": basic.group(1)}
        if basic.group(2):
            schema["format"] = basic.group(2)
        return schema
    if _DEF_NAME_RE.match(token):
        return {"$ref": f"#/definitions/{token}"}
    # A notation this converter doesn't know (future swagger2markup change?).
    # Degrade to a permissive schema and let convert_pdf flag it loudly.
    return {"type": "object", "x-mir-unparsed": token}


def _join_text(cell: str | None) -> str:
    return " ".join(_cell_lines(cell))


def _is_param_header(row: list) -> bool:
    return bool(row) and "".join((row[0] or "").split()) == "Type"


def _is_response_header(row: list) -> bool:
    return bool(row) and "".join((row[0] or "").split()) == "HTTPCode"


def _is_definition_header(row: list) -> bool:
    return bool(row) and "".join((row[0] or "").split()) == "Name"


class _DocumentBuilder:
    """Consumes an ordered stream of headings and tables from the PDF."""

    def __init__(self) -> None:
        self.paths: dict[str, dict[str, dict]] = {}
        self.definitions: dict[str, dict] = {}
        self._op: dict | None = None
        self._op_key: tuple[str, str] | None = None
        self._definition: str | None = None
        self._in_definitions = False
        self._last_table: str | None = None  # 'params' | 'responses' | 'properties'
        self.redefined: set[str] = set()

    # -- headings ---------------------------------------------------------

    def heading(self, line: str) -> None:
        if line == "Definitions":
            self._in_definitions = True
            self._definition = None
            self._last_table = None
            return
        if self._in_definitions:
            if _DEF_NAME_RE.match(line) and line not in ("Name", "Description", "Schema"):
                if line in self.definitions and self.definitions[line]["properties"]:
                    # Same heading twice with content already parsed: two
                    # different inline sub-schemas share a property name.
                    # Their shapes merge; flag it so tests can fail loudly.
                    self.redefined.add(line)
                self._definition = line
                self.definitions.setdefault(line, {"type": "object", "properties": {}})
                self._last_table = None
            return
        match = _OP_RE.match(line)
        if match:
            method, path = match.group(1).lower(), match.group(2)
            if (method, path) == self._op_key:
                return  # section title repeats the page heading
            self._op_key = (method, path)
            self._op = self.paths.setdefault(path, {}).setdefault(
                method, {"parameters": [], "responses": {}}
            )
            self._last_table = None

    # -- tables -----------------------------------------------------------

    def table(self, rows: list[list]) -> None:
        if not rows:
            return
        if self._in_definitions:
            self._definition_table(rows)
        elif self._op is not None:
            self._operation_table(rows)

    def _operation_table(self, rows: list[list]) -> None:
        assert self._op is not None
        if _is_param_header(rows[0]):
            self._last_table = "params"
            rows = rows[1:]
        elif _is_response_header(rows[0]):
            self._last_table = "responses"
            rows = rows[1:]
        if self._last_table == "params":
            for row in rows:
                self._param_row(row)
        elif self._last_table == "responses":
            for row in rows:
                self._response_row(row)

    def _param_row(self, row: list) -> None:
        assert self._op is not None
        if len(row) < 4:
            return
        location = "".join((row[0] or "").split())
        name, required = parse_name_cell(row[1])
        schema = parse_schema_token(row[3])
        if location == "Header" and name == "Accept" and schema:
            # The response content types hide in the Accept header's enum
            # (the source swagger's per-operation "produces").
            enum = schema.get("enum") or (schema.get("items") or {}).get("enum")
            if enum:
                self._op["produces"] = list(enum)
            return
        if not name or location == "Header":
            return
        if location == "Body":
            self._op["parameters"].append(
                {
                    "name": name,
                    "in": "body",
                    "required": required,
                    "schema": schema or {"type": "object"},
                }
            )
        elif location in ("Path", "Query", "FormData"):
            param: dict[str, Any] = {
                "name": name,
                "in": location.lower() if location != "FormData" else "formData",
                "required": True if location == "Path" else required,
            }
            if schema and "$ref" not in schema:
                param.update(schema)
            else:
                param["type"] = "string"
            self._op["parameters"].append(param)

    def _response_row(self, row: list) -> None:
        assert self._op is not None
        if len(row) < 3:
            return
        code = "".join((row[0] or "").split())
        if not code.isdigit():
            return
        response: dict[str, Any] = {"description": _join_text(row[1])}
        schema = parse_schema_token(row[2])
        if schema:
            response["schema"] = schema
        self._op["responses"][code] = response

    def _definition_table(self, rows: list[list]) -> None:
        if _is_definition_header(rows[0]):
            rows = rows[1:]
        if self._definition is None:
            return
        properties = self.definitions[self._definition]["properties"]
        required = self.definitions[self._definition].setdefault("required", [])
        for row in rows:
            if len(row) < 2:
                continue
            name, is_required = parse_name_cell(row[0])
            schema = parse_schema_token(row[-1])
            if not name or schema is None:
                continue
            if len(row) >= 3:
                description = _join_text(row[1])
                if description:
                    schema = {**schema, "description": description}
            properties[name] = schema
            if is_required and name not in required:
                required.append(name)


def _iter_blocks(page) -> list[tuple[float, str, Any]]:
    """Ordered (top, kind, payload) stream of text lines and tables."""
    blocks: list[tuple[float, str, Any]] = []
    tables = page.find_tables()
    boxes = [t.bbox for t in tables]
    for line in page.extract_text_lines():
        mid = (line["top"] + line["bottom"]) / 2
        inside = any(b[1] <= mid <= b[3] for b in boxes)
        if not inside:
            blocks.append((line["top"], "text", line["text"].strip()))
    for t in tables:
        blocks.append((t.bbox[1], "table", t.extract()))
    blocks.sort(key=lambda b: b[0])
    return blocks


def _front_matter(front_pages_text: str) -> tuple[str, str, str]:
    """(title, version, base_path) from the overview page(s).

    Newer PDFs put everything on page one; older ones (2.x era) have a bare
    cover page with the details on the next page, so callers pass the first
    few pages joined.
    """
    title = version = host = ""
    base_path = "/api/v2.0.0"
    lines = [line.strip() for line in front_pages_text.splitlines() if line.strip()]
    if lines:
        title = lines[0]
    for line in lines:
        m = re.match(r"^Version\s*:\s*(\S+)$", line)
        if m:
            version = m.group(1)
        m = re.match(r"^BasePath\s*:\s*(\S+)$", line)
        if m:
            base_path = m.group(1)
        m = re.match(r"^Host\s*:\s*(\S+)$", line)
        if m:
            host = m.group(1)
    if not version and title:
        m = re.match(r"^(\d[\d.]*)\s", title)
        if m:
            version = m.group(1)
    # 2.x-era PDFs split the robot's path across Host (mir.com/api) and
    # BasePath (/v2.0.0); fold the host's path component back in so the
    # document describes what a robot actually serves (/api/v2.0.0).
    if "/" in host:
        prefix = "/" + host.split("/", 1)[1].rstrip("/")
        if prefix != "/" and not base_path.startswith(prefix + "/"):
            base_path = prefix + base_path
    return title, version, base_path


def _inline_sub_schemas(doc: dict) -> None:
    """Fold sub-object tables back into their parents.

    swagger2markup renders inline nested objects as separate snake_case
    headings + tables; the original swagger has them inline. Definitions whose
    names start lowercase are such fragments — inline every reference to them
    and drop them from the top level (matches MiR's official swagger layout).
    """
    subs = {name: d for name, d in doc["definitions"].items() if name[:1].islower()}

    def resolve(node: Any, stack: tuple[str, ...] = ()) -> Any:
        if isinstance(node, dict):
            ref = node.get("$ref", "")
            target = ref.rsplit("/", 1)[-1] if ref.startswith("#/definitions/") else None
            if target in subs and target not in stack:
                inlined = resolve(dict(subs[target]), (*stack, target))
                inlined.update({k: v for k, v in node.items() if k != "$ref"})
                return inlined
            return {k: resolve(v, stack) for k, v in node.items()}
        if isinstance(node, list):
            return [resolve(v, stack) for v in node]
        return node

    doc["paths"] = resolve(doc["paths"])
    doc["definitions"] = {
        name: resolve(d) for name, d in doc["definitions"].items() if name not in subs
    }


def convert_pdf(path: str) -> dict:
    """Parse a MiR REST API PDF into a Swagger 2.0 dict."""
    import pdfplumber  # local import: heavy dependency, scraper-only

    builder = _DocumentBuilder()
    with pdfplumber.open(path) as pdf:
        front = "\n".join(page.extract_text() or "" for page in pdf.pages[:3])
        title, version, base_path = _front_matter(front)
        for page in pdf.pages:
            for _top, kind, payload in _iter_blocks(page):
                if kind == "text":
                    builder.heading(payload)
                else:
                    builder.table(payload)

    for definition in builder.definitions.values():
        if not definition.get("required"):
            definition.pop("required", None)

    doc = {
        "swagger": "2.0",
        "info": {
            "title": title,
            "version": version,
            "description": (
                "Converted from the official MiR REST API PDF by mir-spec-scraper. "
                "Structure (paths, parameters, responses, definitions) mirrors the "
                "official document; prose descriptions may be abbreviated."
            ),
        },
        "basePath": base_path,
        "schemes": ["http"],
        "consumes": ["application/json"],
        "produces": ["application/json"],
        "securityDefinitions": {"Basic": {"type": "basic"}},
        "paths": builder.paths,
        "definitions": builder.definitions,
    }
    warnings = [
        f"inline sub-schema {name!r} defined more than once; shapes merged"
        for name in sorted(builder.redefined)
    ]
    _inline_sub_schemas(doc)
    warnings.extend(_consistency_warnings(doc))
    if warnings:
        doc["x-mir-converter-warnings"] = warnings
    return doc


def _consistency_warnings(doc: dict) -> list[str]:
    """Post-conversion sanity: unknown notations and dangling $refs mean the
    PDF used a shape this converter doesn't understand — fail loudly rather
    than ship a silently-degraded spec."""
    unparsed: set[str] = set()
    dangling: set[str] = set()
    known = set(doc.get("definitions", {}))

    def walk(node: Any) -> None:
        if isinstance(node, dict):
            if "x-mir-unparsed" in node:
                unparsed.add(str(node.pop("x-mir-unparsed")))
            ref = node.get("$ref", "")
            if ref.startswith("#/definitions/") and ref.rsplit("/", 1)[-1] not in known:
                dangling.add(ref.rsplit("/", 1)[-1])
            for value in node.values():
                walk(value)
        elif isinstance(node, list):
            for value in node:
                walk(value)

    walk(doc.get("paths", {}))
    walk(doc.get("definitions", {}))
    warnings = [f"unrecognized schema notation {t!r}" for t in sorted(unparsed)]
    warnings.extend(f"dangling $ref to undefined {name!r}" for name in sorted(dangling))
    return warnings
